CREATE DATABASE zteoa;

USE  zteoa;

# 部门表
CREATE TABLE zteoa_dept(
  id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键，自增',
  name VARCHAR(20) NOT NULL UNIQUE COMMENT '部门名称',
  create_time DATETIME COMMENT '创建时间',
  modify_time DATETIME COMMENT '修改时间'
)ENGINE=INNODB  DEFAULT CHARSET=utf8;

# 角色表
CREATE TABLE zteoa_position(
  id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键，自增',
  name VARCHAR(20) NOT NULL UNIQUE COMMENT '职位名称',
  create_time DATETIME COMMENT '创建时间',
  modify_time DATETIME COMMENT '修改时间'
)ENGINE=INNODB  DEFAULT CHARSET=utf8;

# 员工表
CREATE TABLE zteoa_emp(
  id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键，自增',
  name VARCHAR(20) NOT NULL COMMENT '员工姓名',
  username VARCHAR(20) NOT NULL UNIQUE COMMENT '账号',
  password VARCHAR(20) NOT NULL COMMENT '密码',
  phone CHAR(11) COMMENT '员工手机',
  address VARCHAR(50) COMMENT '家庭住址',
  pid INT NOT NULL COMMENT '职位id',
  did INT NOT NULL COMMENT '部门id',
  create_time DATETIME COMMENT '创建时间',
  modify_time DATETIME COMMENT '修改时间',
  CONSTRAINT FK_DID_EMP FOREIGN KEY (did) REFERENCES zteoa_dept(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FK_PID_EMP FOREIGN KEY (pid) REFERENCES zteoa_position(id) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=INNODB  DEFAULT CHARSET=utf8;

# 商品类别表
CREATE TABLE zteoa_product_category(
  id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键，自增',
  category VARCHAR(20) NOT NULL UNIQUE COMMENT '商品类别名称',
  create_time DATETIME COMMENT '创建时间',
  modify_time DATETIME COMMENT '修改时间'
)ENGINE=INNODB  DEFAULT CHARSET=utf8;

# 商品表
CREATE TABLE zteoa_product(
  id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键，自增',
  category_id INT NOT NULL COMMENT '商品类别',
  name VARCHAR(20) NOT NULL COMMENT '商品名称',
  price DECIMAL NOT NULL COMMENT '商品价格',
  num INT NOT NULL COMMENT '商品库存',
  create_time DATETIME COMMENT '创建时间',
  modify_time DATETIME COMMENT '修改时间',
  CONSTRAINT FK_CID_ZPC FOREIGN KEY (category_id) REFERENCES zteoa_product_category(id) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=INNODB  DEFAULT CHARSET=utf8;

# 办公用品申请
CREATE TABLE zteoa_receive(
  id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键，自增',
  eid INT NOT NULL COMMENT '申请人id',
  pid INT NOT NULL COMMENT '商品id',
  num INT NOT NULL COMMENT '申请数量',
  category VARCHAR(20) NOT NULL COMMENT '申请类别',
  reason VARCHAR(200) NOT NULL COMMENT '申请原因',
  create_time DATETIME COMMENT '创建时间',
  modify_time DATETIME COMMENT '修改时间',
  CONSTRAINT FK_EID_EMP FOREIGN KEY (eid) REFERENCES zteoa_emp(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FK_PID_PRODUCT FOREIGN KEY (pid) REFERENCES zteoa_product(id) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=INNODB  DEFAULT CHARSET=utf8;

# 会议室表
CREATE TABLE zteoa_boardroom(
  id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键，自增',
  name VARCHAR(20) NOT NULL COMMENT '会议室名称',
  address VARCHAR(50) NOT NULL COMMENT '会议室地址',
  is_use TINYINT NOT NULL COMMENT '是否使用',
  create_time DATETIME COMMENT '创建时间',
  modify_time DATETIME COMMENT '修改时间'
)ENGINE=INNODB  DEFAULT CHARSET=utf8;

# 会议室申请表
CREATE TABLE zteoa_boardroom_apply(
  id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键，自增',
  start DATETIME NOT NULL COMMENT '开始时间',
  end DATETIME NOT NULL COMMENT '结束时间',
  eid INT NOT NULL COMMENT '申请人',
  is_agree BIT NOT NULL COMMENT '是否同意',
  create_time DATETIME COMMENT '创建时间',
  modify_time DATETIME COMMENT '修改时间',
  CONSTRAINT FK_ZBAEID_EMP FOREIGN KEY (eid) REFERENCES zteoa_emp(id) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=INNODB  DEFAULT CHARSET=utf8;

# 会议室设施
CREATE TABLE zteoa_boardroom_facilities(
  id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键，自增',
  pid INT NOT NULL COMMENT '设施id,与用品表外键关联',
  num INT NOT NULL COMMENT '设施数量',
  bid INT NOT NULL COMMENT '所属会议室',
  create_time DATETIME COMMENT '创建时间',
  modify_time DATETIME COMMENT '修改时间',
  CONSTRAINT FK_ZBFPID_PRODUCT FOREIGN KEY (pid) REFERENCES zteoa_product(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FK_ZBFBID_ZB FOREIGN KEY (bid) REFERENCES zteoa_boardroom(id) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=INNODB  DEFAULT CHARSET=utf8;